sonar.projectKey=MrunalSPatil_EmailNotificationService
sonar.projectName=springboot-email-service
sonar.projectVersion=1.0.0
sonar.sources=src/main
sonar.tests=src/test
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml