server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mrunalshambhurajpatil97@gmail.com
spring.mail.password=trpo oqnc xqfy bjmy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
